# -*- coding: utf-8 -*-
"""Robotsitosensual.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHx1WN5UEpeYwem7-GnXsKUpS_cnf7fB
"""

def usuario():  # define la función llamada usuario
    nombre = input("Por favor ingrese su nombre: ")  #
    print(f"Hola, {nombre}! Encantado de conocerte.")
    print()
    print(f"¿En qué te puedo ayudar, {nombre}?")

usuario()